package modelo;
// Generated 22-may-2018 12:22:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Asignaturas generated by hbm2java
 */
public class Asignaturas  implements java.io.Serializable {
    private Integer codigo;
    private Profesores profesores;
    private String nombre;
    private String codigo_profesor;
    private String nombre_profesor;
    private String apellido1_profesor;
    private String apellido2_profesor;
    private String dni_profesor;
    private String codigo_grupo;
    private String nombre_grupo;
    private String codigo_curso;
    private String nombre_curso;
    private int codigoCurso;
    private int codigoGrupo;
    private int codigoProfesor;
    private Set matriculases = new HashSet(0);
    private Set horarioses = new HashSet(0);

    public Asignaturas() {
    }

    public Asignaturas(Profesores profesores, String nombre, int codigoCurso, int codigoGrupo) {
        this.profesores = profesores;
        this.nombre = nombre;
        this.codigoCurso = codigoCurso;
        this.codigoGrupo = codigoGrupo;
    }
    public Asignaturas(Profesores profesores, String nombre, int codigoCurso, int codigoGrupo, Set matriculases, Set horarioses) {
       this.profesores = profesores;
       this.nombre = nombre;
       this.codigoCurso = codigoCurso;
       this.codigoGrupo = codigoGrupo;
       this.matriculases = matriculases;
       this.horarioses = horarioses;
    }
    
    public Asignaturas(int codigo, String nombre, int codigoProfesor, int codigoCurso, int codigoGrupo) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.codigoCurso = codigoCurso;
       this.codigoGrupo = codigoGrupo;
       this.codigoProfesor = codigoProfesor;
    }
    
    public Asignaturas(int registro, String nombre,String codigo_profesor,String nombre_profesor,String apellido1_profesor,String apellido2_profesor,String dni_profesor,String codigo_grupo,String nombre_grupo,String codigo_curso,String nombre_curso){
        this.codigo=registro;
        this.nombre=nombre;
        this.codigo_profesor=codigo_profesor;
        this.nombre_profesor=nombre_profesor;
        this.apellido1_profesor=apellido1_profesor;
        this.apellido2_profesor=apellido2_profesor;
        this.dni_profesor=dni_profesor;
        this.codigo_grupo=codigo_grupo;
        this.nombre_grupo=nombre_grupo;
        this.codigo_curso=codigo_curso;
        this.nombre_curso=nombre_curso;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Profesores getProfesores() {
        return this.profesores;
    }
    
    public void setProfesores(Profesores profesores) {
        this.profesores = profesores;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getCodigoCurso() {
        return this.codigoCurso;
    }
    
    public void setCodigoCurso(int codigoCurso) {
        this.codigoCurso = codigoCurso;
    }
    public int getCodigoGrupo() {
        return this.codigoGrupo;
    }
    
    public void setCodigoGrupo(int codigoGrupo) {
        this.codigoGrupo = codigoGrupo;
    }
    public Set getMatriculases() {
        return this.matriculases;
    }
    
    public void setMatriculases(Set matriculases) {
        this.matriculases = matriculases;
    }
    public Set getHorarioses() {
        return this.horarioses;
    }
    
    public void setHorarioses(Set horarioses) {
        this.horarioses = horarioses;
    }

    public String getCodigo_profesor() {
        return codigo_profesor;
    }

    public void setCodigo_profesor(String codigo_profesor) {
        this.codigo_profesor = codigo_profesor;
    }
    
    public String getNombre_profesor() {
        return nombre_profesor;
    }

    public void setNombre_profesor(String nombre_profesor) {
        this.nombre_profesor = nombre_profesor;
    }
    
    public String getApellido1_profesor() {
        return apellido1_profesor;
    }

    public void setApellido1_profesor(String apellido1_profesor) {
        this.apellido1_profesor = apellido1_profesor;
    }
    
    public String getApellido2_profesor() {
        return apellido2_profesor;
    }

    public void setApellido2_profesor(String apellido2_profesor) {
        this.apellido2_profesor = apellido2_profesor;
    }
    
    public String getDNI_profesor() {
        return dni_profesor;
    }

    public void setDNI_profesor(String dni_profesor) {
        this.dni_profesor = dni_profesor;
    }
    
    public String getCodigo_grupo() {
        return codigo_grupo;
    }

    public void setCodigo_grupo(String codigo_grupo) {
        this.codigo_grupo = codigo_grupo;
    }
    
    public String getNombre_grupo() {
        return nombre_grupo;
    }

    public void setNombre_grupo(String nombre_grupo) {
        this.nombre_grupo = nombre_grupo;
    }

    public String getCodigo_curso() {
        return codigo_curso;
    }

    public void setCodigo_curso(String codigo_curso) {
        this.codigo_curso = codigo_curso;
    }
    
    public String getNombre_curso() {
        return nombre_curso;
    }

    public void setNombre_curso(String nombre_curso) {
        this.nombre_curso = nombre_curso;
    }
}


