package modelo;
// Generated 22-may-2018 12:22:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cursos generated by hbm2java
 */
public class Cursos  implements java.io.Serializable {
     private Integer codigo;
     private String nombre;
     private Set gruposes = new HashSet(0);

    public Cursos() {
    }

    public Cursos(int codigo) {
        this.codigo = codigo;
    }
    public Cursos(String nombre) {
        this.nombre = nombre;
    }
    public Cursos(String nombre, Set gruposes) {
       this.nombre = nombre;
       this.gruposes = gruposes;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getGruposes() {
        return this.gruposes;
    }
    
    public void setGruposes(Set gruposes) {
        this.gruposes = gruposes;
    }
}