package modelo;
// Generated 22-may-2018 12:22:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos  implements java.io.Serializable {


     private Integer codigo;
     private Profesores profesores;
     private String nombre;
     private String director;
     private String nombre_director;
     private String apellido1_director;
     private String apellido2_director;
     private String dni_director;
     private Set profesoreses = new HashSet(0);

    public Departamentos() {
    }
    
    public Departamentos(Profesores profesores,String nombre) {
       this.profesores = profesores;
       this.nombre = nombre;
    }

    public Departamentos(String nombre,String director) {
       this.director = director;
       this.nombre = nombre;
    }
	
    public Departamentos(String nombre) {
        this.nombre = nombre;
    }
    public Departamentos(Profesores profesores, String nombre, Set profesoreses) {
       this.profesores = profesores;
       this.nombre = nombre;
       this.profesoreses = profesoreses;
    }
    
    public Departamentos(int codigo, String nombre) {
       this.codigo = codigo;
       this.nombre = nombre;
    }
    
    public Departamentos(int codigo, String nombre, String director, String nombre_director, String apellido1_director, String apellido2_director, String dni_director){
        this.codigo=codigo;
        this.nombre=nombre;
        this.director=director;
        this.nombre_director=nombre_director;
        this.apellido1_director=apellido1_director;
        this.apellido2_director=apellido2_director;
        this.dni_director=dni_director;
    }
    
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Profesores getProfesores() {
        return this.profesores;
    }
    
    public void setProfesores(Profesores profesores) {
        this.profesores = profesores;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getProfesoreses() {
        return this.profesoreses;
    }
    
    public void setProfesoreses(Set profesoreses) {
        this.profesoreses = profesoreses;
    }

    public String getDirector() {
        return director;
    }

    public void setDirector(String director) {
        this.director = director;
    }

    public String getNombre_director() {
        return nombre_director;
    }

    public void setNombre_director(String nombre_director) {
        this.nombre_director = nombre_director;
    }
    
    public String getApellido1_director() {
        return apellido1_director;
    }

    public void setApellido1_director(String apellido1_director) {
        this.apellido1_director = apellido1_director;
    }
    
    public String getApellido2_director() {
        return apellido2_director;
    }

    public void setApellido2_director(String apellido2_director) {
        this.apellido2_director = apellido2_director;
    }
    
    public String getDNI_director() {
        return dni_director;
    }

    public void setDNI_director(String dni_director) {
        this.dni_director = dni_director;
    }
}


