package modelo;
// Generated 22-may-2018 12:22:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grupos generated by hbm2java
 */
public class Grupos  implements java.io.Serializable {


    private Integer codigo;
    private Cursos cursos;
    private String nombre;
    private Integer codigoTutor;
    private String curso;
    private String nombre_curso;
    private String tutor;
    private String nombre_tutor;
    private Set asignacionAulases = new HashSet(0);
    private Set alumnoses = new HashSet(0);

    public Grupos() {
    }
    
    public Grupos(Cursos cursos, String nombre, Integer codigoTutor) {
        this.cursos = cursos;
        this.nombre = nombre;
        this.codigoTutor = codigoTutor;
    }
    public Grupos(Cursos cursos, String nombre, Integer codigoTutor, Set asignacionAulases, Set alumnoses) {
       this.cursos = cursos;
       this.nombre = nombre;
       this.codigoTutor = codigoTutor;
       this.asignacionAulases = asignacionAulases;
       this.alumnoses = alumnoses;
    }
    
    public Grupos(int registro, String nombre, String curso, String nombre_curso, String tutor, String nombre_tutor){
        this.codigo=registro;
        this.nombre=nombre;
        this.curso=curso;
        this.nombre_curso=nombre_curso;
        this.tutor=tutor;
        this.nombre_tutor=nombre_tutor;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Cursos getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Cursos cursos) {
        this.cursos = cursos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getCodigoTutor() {
        return this.codigoTutor;
    }
    
    public void setCodigoTutor(Integer codigoTutor) {
        this.codigoTutor = codigoTutor;
    }
    public Set getAsignacionAulases() {
        return this.asignacionAulases;
    }
    
    public void setAsignacionAulases(Set asignacionAulases) {
        this.asignacionAulases = asignacionAulases;
    }
    public Set getAlumnoses() {
        return this.alumnoses;
    }
    
    public void setAlumnoses(Set alumnoses) {
        this.alumnoses = alumnoses;
    }
    
    public String getCurso() {
        return curso;
    }

    public void setCurso(String curso) {
        this.curso = curso;
    }
    
    public String getNombre_curso() {
        return nombre_curso;
    }
    
    public void setNombre_curso(String nombre_curso) {
        this.nombre_curso = nombre_curso;
    }

    public String getTutor() {
            return tutor;
    }

    public void setTutor(String tutor) {
        this.tutor = tutor;
    }
    
    public String getNombre_tutor() {
        return nombre_tutor;
    }
    
    public void setNombre_tutor(String nombre_tutor) {
        this.nombre_tutor = nombre_tutor;
    }
}


