package modelo;
// Generated 22-may-2018 12:22:28 by Hibernate Tools 4.3.1



/**
 * MatriculasId generated by hbm2java
 */
public class MatriculasId  implements java.io.Serializable {


     private int codigoCurso;
     private int codigoAlumno;

    public MatriculasId() {
    }

    public MatriculasId(int codigoCurso, int codigoAlumno) {
       this.codigoCurso = codigoCurso;
       this.codigoAlumno = codigoAlumno;
    }
   
    public int getCodigoCurso() {
        return this.codigoCurso;
    }
    
    public void setCodigoCurso(int codigoCurso) {
        this.codigoCurso = codigoCurso;
    }
    public int getCodigoAlumno() {
        return this.codigoAlumno;
    }
    
    public void setCodigoAlumno(int codigoAlumno) {
        this.codigoAlumno = codigoAlumno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MatriculasId) ) return false;
		 MatriculasId castOther = ( MatriculasId ) other; 
         
		 return (this.getCodigoCurso()==castOther.getCodigoCurso())
 && (this.getCodigoAlumno()==castOther.getCodigoAlumno());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodigoCurso();
         result = 37 * result + this.getCodigoAlumno();
         return result;
   }   


}


