package modelo;
// Generated 22-may-2018 12:22:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profesores generated by hbm2java
 */
public class Profesores  implements java.io.Serializable {
    private Integer codigo;
    private Departamentos departamentos;
    private String dni;
    private String nombre;
    private String apellido1;
    private String apellido2;
    private String departamento;
    private String nombre_departamento;
    private Set departamentoses = new HashSet(0);
    private Set tutoriases = new HashSet(0);
    private Set asignaturases = new HashSet(0);
     
    public Profesores() {
    }

	
    public Profesores(Departamentos departamentos, String dni, String nombre, String apellido1, String apellido2) {
        this.departamentos = departamentos;
        this.dni = dni;
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.apellido2 = apellido2;
    }
    public Profesores(Departamentos departamentos, String dni, String nombre, String apellido1, String apellido2, Set departamentoses, Set tutoriases, Set asignaturases) {
       this.departamentos = departamentos;
       this.dni = dni;
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.departamentoses = departamentoses;
       this.tutoriases = tutoriases;
       this.asignaturases = asignaturases;
    }
    
    public Profesores(int registro, String dni, String nombre, String apellido1, String apellido2, String departamento, String nombre_departamento){
        this.codigo=registro;
        this.dni=dni;
        this.nombre=nombre;
        this.apellido1=apellido1;
        this.apellido2=apellido2;
        this.departamento=departamento;
        this.nombre_departamento=nombre_departamento;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Departamentos getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Departamentos departamentos) {
        this.departamentos = departamentos;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public Set getDepartamentoses() {
        return this.departamentoses;
    }
    
    public void setDepartamentoses(Set departamentoses) {
        this.departamentoses = departamentoses;
    }
    public Set getTutoriases() {
        return this.tutoriases;
    }
    
    public void setTutoriases(Set tutoriases) {
        this.tutoriases = tutoriases;
    }
    public Set getAsignaturases() {
        return this.asignaturases;
    }
    
    public void setAsignaturases(Set asignaturases) {
        this.asignaturases = asignaturases;
    }

    public String getDepartamento() {
        return departamento;
    }

    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    
    public String getNombre_departamento() {
        return nombre_departamento;
    }
    
    public void setNombre_departamento(String nombre_departamento) {
        this.nombre_departamento = nombre_departamento;
    }
}