package modelo;
// Generated 22-may-2018 12:22:28 by Hibernate Tools 4.3.1



/**
 * Tutorias generated by hbm2java
 */
public class Tutorias  implements java.io.Serializable {
    private Integer codigo;
    private Profesores profesores;
    private String dia;
    private String comienzo;
    private String fin;
    private String codigo_profesor;
    private String nombre_profesor;
    private String apellido1_profesor;
    private String apellido2_profesor;
    private String dni_profesor;

    public Tutorias() {
    }

    public Tutorias(Profesores profesores, String dia, String comienzo, String fin) {
       this.profesores = profesores;
       this.dia = dia;
       this.comienzo = comienzo;
       this.fin = fin;
    }
   
    public Tutorias(int registro, String dia, String comienzo, String fin, String codigo_profesor, String nombre_profesor, String apellido1_profesor, String apellido2_profesor, String dni_profesor){
        this.codigo=registro;
        this.dia=dia;
        this.comienzo=comienzo;
        this.fin=fin;
        this.codigo_profesor=codigo_profesor;
        this.nombre_profesor=nombre_profesor;
        this.apellido1_profesor=apellido1_profesor;
        this.apellido2_profesor=apellido2_profesor;
        this.dni_profesor=dni_profesor;
    }
    
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Profesores getProfesores() {
        return this.profesores;
    }
    
    public void setProfesores(Profesores profesores) {
        this.profesores = profesores;
    }
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }
    public String getComienzo() {
        return this.comienzo;
    }
    
    public void setComienzo(String comienzo) {
        this.comienzo = comienzo;
    }
    public String getFin() {
        return this.fin;
    }
    
    public void setFin(String fin) {
        this.fin = fin;
    }

    public String getCodigo_profesor() {
        return codigo_profesor;
    }

    public void setCodigo_profesor(String codigo_profesor) {
        this.codigo_profesor = codigo_profesor;
    }
    
    public String getNombre_profesor() {
        return nombre_profesor;
    }

    public void setNombre_profesor(String nombre_profesor) {
        this.nombre_profesor = nombre_profesor;
    }
    
    public String getApellido1_profesor() {
        return apellido1_profesor;
    }

    public void setApellido1_profesor(String apellido1_profesor) {
        this.apellido1_profesor = apellido1_profesor;
    }
    
    public String getApellido2_profesor() {
        return apellido2_profesor;
    }

    public void setApellido2_profesor(String apellido2_profesor) {
        this.apellido2_profesor = apellido2_profesor;
    }
    
    public String getDNI_profesor() {
        return dni_profesor;
    }

    public void setDNI_profesor(String dni_profesor) {
        this.dni_profesor = dni_profesor;
    }
}